### ISSUE TITLE
Use IPC for Events

### ISSUE THREAD

**Issue by sagedemage** [sagedemage/TextEditor2#10]
**Describe the feature**
Use IPC to perform events on the renderer.

## Tasks
- [x] Use IPC for opening a file
- [x] Use IPC for saving a file
### Extras
- [x] Move js files to the source directory

**Comment by sagedemage** [comment]
```
git fetch origin
git checkout 10-use-ipc-for-events
```
