### ISSUE TITLE
Use Vite Plugin with Electron Forge

### ISSUE THREAD

**Issue by sagedemage** [sagedemage/TextEditor2#20]
**Describe the feature**
Use the Vite plugin with Electron Forge's plugin system.

## Reason
I want to use Vite to improve the **development experience** of the app. Vite supports HMR (Hot Module Replacement) to provide instant updates without reloading the page or stopping and starting the app which destroys the application state.

## Tasks
- [x] Setup Vite plugin

## Extras
- [x] Only have `npm run lint` command for linting the project
- [x] Rename win variables

## Resources
- [Hot Module Replacement](https://vitejs.dev/guide/features#hot-module-replacement)

**Comment by sagedemage** [comment]
```
git fetch origin
git checkout 20-use-vite-plugin-with-electron-forge
```
